branch-protection:
  orgs:
    istio-ecosystem:
      repos:
        sail-operator:
          branches:
            pre-main:
              protect: true
              required_pull_request_reviews:
                required_approving_review_count: 1
              unmanaged: false
tide:
  merge_method:
    istio-ecosystem/sail-operator: squash
  queries:
  - author: maistra-bot
    labels:
    - auto-merge
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    repos:
    - istio-ecosystem/sail-operator
  - labels:
    - okay to merge
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    repos:
    - istio-ecosystem/sail-operator
    reviewApprovedRequired: true
