build_root:
  image_stream_tag:
    name: maistra-builder
    namespace: ci
    tag: "2.3"
  use_build_cache: true
resources:
  '*':
    limits:
      memory: 16Gi
    requests:
      cpu: "4"
      memory: 4Gi
tests:
- as: istio-unit-2-3
  commands: |
    make -e T=-v build racetest binaries-test \
    BUILD_WITH_CONTAINER="0" \
    GOBIN="/gobin" \
    GOCACHE="/tmp/cache" \
    GOMODCACHE="/tmp/cache" \
    GOFLAGS="-mod=vendor" \
    XDG_CACHE_HOME="/tmp/cache" \
    ISTIO_ENVOY_BASE_URL="https://storage.googleapis.com/maistra-prow-testing/proxy"
  container:
    from: src
  timeout: 4h0m0s
- as: istio-lint-2-3
  commands: |
    make lint \
    BUILD_WITH_CONTAINER="0" \
    GOBIN="/gobin" \
    GOCACHE="/tmp/cache" \
    GOMODCACHE="/tmp/cache" \
    GOFLAGS="-mod=vendor" \
    XDG_CACHE_HOME="/tmp/cache" \
    ISTIO_ENVOY_BASE_URL="https://storage.googleapis.com/maistra-prow-testing/proxy"
  container:
    from: src
- as: istio-gencheck-2-3
  commands: |
    make gen-check \
    BUILD_WITH_CONTAINER="0" \
    GOBIN="/gobin" \
    GOCACHE="/tmp/cache" \
    GOMODCACHE="/tmp/cache" \
    GOFLAGS="-mod=vendor" \
    XDG_CACHE_HOME="/tmp/cache" \
    ISTIO_ENVOY_BASE_URL="https://storage.googleapis.com/maistra-prow-testing/proxy"
  container:
    from: src
- as: istio-integration-pilot-2-3
  cluster_claim:
    architecture: amd64
    cloud: aws
    owner: openshift-ci
    product: ocp
    timeout: 1h0m0s
    version: "4.11"
  steps:
    test:
    - as: test
      commands: make test.integration.pilot.kube.presubmit BUILD_WITH_CONTAINER="0"
      from: src
      resources:
        requests:
          cpu: "1"
          memory: 1Gi
      timeout: 4h0m0s
    workflow: generic-claim
zz_generated_metadata:
  branch: maistra-2.3
  org: maistra
  repo: istio
