base_images:
  cli:
    name: "4.10"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: maistra-builder
    namespace: ci
    tag: "2.4"
  use_build_cache: true
releases:
  latest:
    release:
      channel: stable
      version: "4.10"
resources:
  '*':
    limits:
      memory: 16Gi
    requests:
      cpu: "2"
      memory: 4Gi
tests:
- as: merge-upstream-istio-3.0
  commands: |
    ./tools/automator-main.sh \
    --org=maistra \
    --repo=istio \
    --branch=maistra-3.0 \
    --token-path=/creds-github/github-token \
    "--title=Automator: merge upstream changes to $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH" \
    "--labels=merge strategy" \
    --modifier=merge_upstream_istio_master \
    --merge-repository=https://github.com/istio/istio.git \
    --merge-branch=master \
    --merge-failure-notify=@maistra/release-managers-2-4 \
    --merge-strategy=merge
  container:
    from: src
  cron: 00 05 * * 1-5
zz_generated_metadata:
  branch: main
  org: maistra
  repo: test-infra
